/*
  defaults.js
  This file holds the default settings for the extension.
  It is loaded before other scripts so they can read these defaults.
*/

// Use globalThis so this works in content scripts, the popup, and options pages.
const MV_DEFAULT_SETTINGS = {
  // If a word/phrase from this list appears in the title or channel,
  // the video is classified as MUSIC immediately.
  strongMusicKeywords: [
    "official music video",
    "official video",
    "music video",
    "official mv",
    "mv",
    "vevo",
    "lyric video",
    "lyrics",
    "lyricvideo",
    "audio (official)",
    "music",
    "official music video",
    "official video",
    "music video",
    "official mv",
    "mv",
    "official audio",
    "audio (official)",
    "official audio",
    "lyric video",
    "lyrics",
    "lyric video",
    "lyricvideo",
    "audio",
    "visualizer",
    "official visualizer",
    "audio visualizer",
    "official single",
    "single (official)",
    "album track",
    "album (official)",
    "ep (official)",
    "soundtrack (OST)",
    "ost",
    "original soundtrack",
    "original score",
    "score (film score)",
    "theme song",
    "theme (official)",
    "theme (soundtrack)",
    "studio recording",
    "studio version",
    "master (remaster)",
    "remastered (official)",
    "VEVO",
    "HQ audio",
    "HD audio",
    "radio edit",
    "official release",
    "official performance",
    "concert clip",
    "full album",
    "full track"
  ],

  // These words/phrases are a weaker signal for music.
  // We treat these as MUSIC unless the duration is extremely short or long.
  moderateMusicKeywords: [
    "remix",
    "feat.",
    "ft.",
    "feat",
    "featuring",
    "single",
    "album",
    "cover",
    "studio version",
    "radio edit",
    "cover",
    "acoustic",
    "unplugged",
    "session",
    "live",
    "live performance",
    "live at",
    "live from",
    "concert",
    "gig",
    "festival set",
    "DJ set",
    "set (DJ set)",
    "performance",
    "performance video",
    "piano version",
    "orchestral version",
    "band version",
    "instrumental",
    "instrumental version",
    "karaoke",
    "singalong",
    "arrangement",
    "arranged",
    "medley",
    "mashup",
    "remix",
    "club mix",
    "extended mix",
    "radio mix",
    "radio edit",
    "edit (when paired with music tokens)",
    "rework",
    "reimagined",
    "redux",
    "stripped",
    "studio session",
    "rehearsal (if musical context)",
    "jam session",
    "session recording",
    "backing track",
    "backing vocals",
    "choir",
    "choral",
    "ensemble",
    "quartet",
    "trio",
    "duet",
    "solo (piano solo, violin solo, cello solo)",
    "serenade",
    "cantata",
    "aria",
    "nocturne",
    "sonata",
    "concerto",
    "prelude",
    "fugue",
    "etude",
    "rhapsody",
    "overture",
    "symphony",
    "movement",
    "chamber music",
    "score cue",
    "soundtrack cue",
    "cinematic score",
    "film score",
    "trailer score (contextual: often musical)",
    "OST cue",
    "theme (contextual)",
    "studio take",
    "session take",
    "performance take",
    "visual album",
    "audiovisual",
    "music documentary (contextual - still music-related)"
  ],

  // If a word/phrase from this list appears in the title or channel,
  // the video is classified as NON-MUSIC immediately.
  nonMusicKeywords: [
    "interview",
    "review",
    "gameplay",
    "tutorial",
    "reaction",
    "news",
    "vlog",
    "podcast",
    "lecture",
    "commentary",
    "let's play",
    "gaming",
    "behind the scenes",
    "trailer",
    "skit",
    "interview",
    "interviews",
    "q&a",
    "q and a",
    "podcast",
    "podcast episode",
    "podcast clip",
    "reaction",
    "reaction video",
    "review",
    "review of",
    "unboxing",
    "haul",
    "tutorial",
    "how to",
    "how-to",
    "walkthrough",
    "guide",
    "demo",
    "demonstration",
    "tech demo",
    "setup",
    "build",
    "case mod",
    "teardown",
    "product review",
    "first impressions",
    "impressions",
    "commentary",
    "commentator",
    "analysis",
    "analysis of",
    "essay",
    "explainer",
    "explain",
    "explanation",
    "news",
    "news report",
    "report",
    "press conference",
    "press release",
    "documentary",
    "docu",
    "biography",
    "biopic clip",
    "clip",
    "scene",
    "trailer",
    "movie trailer",
    "film clip",
    "highlights",
    "sports highlights",
    "game highlights",
    "gameplay",
    "let's play",
    "lets play",
    "speedrun",
    "speed run",
    "walkthrough",
    "challenge",
    "prank",
    "skit",
    "sketch",
    "comedy sketch",
    "standup",
    "stand-up",
    "roast",
    "roast video",
    "prank compilation",
    "vlog",
    "vloggers",
    "daily vlog",
    "daily update",
    "stream",
    "livestream",
    "live stream",
    "stream highlights",
    "live q&a",
    "panel discussion",
    "debate",
    "talk show",
    "sermon",
    "lecture",
    "class",
    "tutorial series",
    "study with me",
    "asmr (often non-musical ambient)",
    "ambience",
    "field recording",
    "nature sounds",
    "sound effects",
    "foley",
    "ambience loop",
    "loop (ambience)",
    "compilation (contextual - ambiguous but often non-music editorial)",
    "montage (contextual)",
    "reaction + review",
    "commentary + reaction",
    "top 10",
    "listicle",
    "ranking",
    "countdown",
    "how it's made",
    "behind the scenes (contextual-often non-music unless musical BTS)",
    "office hours",
    "explanation video",
    "startup pitch",
    "investor pitch",
    "code tutorial",
    "programming tutorial",
    "lecture hall",
    "classroom",
    "DIY",
    "crafts",
    "cooking",
    "recipe",
    "makeup tutorial",
    "fashion haul",
    "sewing tutorial",
    "gaming news",
    "cast",
    "then & now",
    "then and now",
    "from hogwarts to today",
    "hogwarts",
    "harry potter",
    "ice cream",
    "ice cream trick",
    "feels impossible"
  ],

  // Channel name tokens that increase confidence the channel is music-related.
  channelMusicTokens: [
    "vevo",
    "official",
    "records",
    "music",
    "band",
    "orchestra",
    "symphony",
    "choir",
    "dj",
    "label",
    "vevo",
    "official",
    "official channel",
    "records",
    "recordings",
    "music",
    "music channel",
    "musicvideos",
    "music videos",
    "musicvideo",
    "band",
    "band official",
    "band channel",
    "orchestra",
    "symphony",
    "philharmonic",
    "choir",
    "choral",
    "quartet",
    "trio",
    "ensemble",
    "soloist",
    "pianist",
    "pianist official",
    "violinist",
    "cellist",
    "guitarist",
    "singer",
    "vocalist",
    "vocalist official",
    "dj",
    "djs",
    "dj set",
    "label",
    "records (label suffix, e.g., \"xyz records\")",
    "productions",
    "studios",
    "studio productions",
    "studio sessions",
    "music studio",
    "classical",
    "classical music",
    "opera",
    "opera house",
    "conservatory",
    "academy of music",
    "chamber music",
    "symphony orchestra",
    "philharmonic orchestra",
    "live music",
    "live concert",
    "concert hall",
    "concertband",
    "choirmasters",
    "the piano guys",
    "pianoguys",
    "thepianoguys",
    "2cellos",
    "2CELLOS",
    "taylor davis",
    "andre rieu",
    "andr\u00e9 rieu",
    "cello duo",
    "string quartet",
    "string quartet official",
    "acoustic \u2022 (channel names that include \"acoustic\")",
    "covers (channel name contains \"covers\")",
    "covers channel",
    "cover band",
    "band covers",
    "music label",
    "record label",
    "music productions",
    "music factory",
    "orchestra official",
    "symphonic",
    "arranger (channel with arranger/arrangements)",
    "tribute band",
    "choir official",
    "choir recordings",
    "music academy",
    "music conservatory"
  ],

  // Default policy when we are NOT confident.
  // "show" = assume it is music (do NOT hide).
  // "hide" = assume it is non-music (hide).
  defaultPolicy: "show",

  // Whether blocked items should be shown (for undo / review).
  showBlocked: false,

  // Debounce time for DOM scanning to reduce thrashing.
  debounceMs: 60,

  // Debug mode: when true, logs details to the console and shows a small badge.
  debugMode: false
};

// Expose on globalThis for other scripts.
globalThis.MV_DEFAULT_SETTINGS = MV_DEFAULT_SETTINGS;
